Repository rp-s-tech/SS14_Workstation, pull requests merged in 2025-07, with the labels that each got.

#54 Добавление синт ткани для принтера протезов
  Resources/Locale/ru-RU/_RPSX/catalog/fills/Crates/medical.ftl
  Resources/Locale/ru-RU/_RPSX/entities/objects/Materials/materials.ftl
  Resources/Locale/ru-RU/_RPSX/materials/materials.ftl
  Resources/Locale/ru-RU/_RPSX/stack/stacks.ftl
  Resources/Prototypes/DarkStation/MainGame/Catalog/Cargo/cargo_bionics.yml
  Resources/Prototypes/DarkStation/MainGame/Entities/Structures/Storage/Crates/crates.yml
  Resources/Prototypes/_RPSX/Catalog/Cargo/cargo_medical.yml
  Resources/Prototypes/_RPSX/Catalog/Fills/Crates/medical.yml
  Resources/Prototypes/_RPSX/Entities/Objects/Materials/materials.yml
  Resources/Prototypes/_RPSX/Reagents/Materials/materials.yml
  Resources/Prototypes/_RPSX/Recipes/Lathes/medical.yml
  Resources/Prototypes/_RPSX/Stacks/Materials/materials.yml
  Resources/Textures/_RPSX/Objects/Materials/materials.rsi/meta.json
  Resources/Textures/_RPSX/Objects/Materials/materials.rsi/syntheticCloth-inhand-left.png
  Resources/Textures/_RPSX/Objects/Materials/materials.rsi/syntheticCloth-inhand-right.png
  Resources/Textures/_RPSX/Objects/Materials/materials.rsi/syntheticCloth.png
  Resources/Textures/_RPSX/Objects/Materials/materials.rsi/syntheticCloth_2.png
  Resources/Textures/_RPSX/Objects/Materials/materials.rsi/syntheticCloth_3.png
Labels: size/M, Changes: No C#, S: Untriaged, Changes: Sprites

#63 Another actions additions
  .github/workflows/publish-testing.yml
  .github/workflows/publish.yml
  .github/workflows/test-packaging.yml
  .github/workflows/unified-rpsx-action
Labels: size/M, Changes: No C#

#65 test
  .github/workflows/test-packaging.yml
  .github/workflows/unified-rpsx-action.yml
  .github/workflows/yaml-linter.yml
Labels: size/M, Changes: No C#

#78 Revert some license changes
  .github/rsi-schema.json
  Resources/Textures/Exodus/Clothing/Head/Hardsuits/salvage_maximal.rsi/meta.json
  Resources/Textures/Exodus/Mobs/Customization/Vulpkanin/vulpkanin_arm.rsi/meta.json
  Resources/Textures/Exodus/Mobs/Customization/Vulpkanin/vulpkanin_ears.rsi/meta.json
  Resources/Textures/Exodus/Mobs/Customization/Vulpkanin/vulpkanin_foot.rsi/meta.json
  Resources/Textures/Exodus/Mobs/Customization/Vulpkanin/vulpkanin_hand.rsi/meta.json
  Resources/Textures/Exodus/Mobs/Customization/Vulpkanin/vulpkanin_leg.rsi/meta.json
  Resources/Textures/Exodus/Mobs/Customization/Vulpkanin/vulpkanin_snout.rsi/meta.json
  Resources/Textures/Exodus/Mobs/Customization/Vulpkanin/vulpkanin_torso.rsi/meta.json
  Resources/Textures/Exodus/Objects/Fun/toys.rsi/meta.json
  Resources/Textures/Exodus/Objects/Specific/Medical/mechanical_injector.rsi/meta.json
  Resources/Textures/Exodus/Structures/Lighting/Decoration/elmosfire.rsi/meta.json
  Resources/Textures/Exodus/Structures/Piping/Atmospherics/tiny_fan.rsi/meta.json
  Resources/Textures/Exodus/Tiles/Misc/floortrap.rsi/meta.json
Labels: size/S, Changes: No C#

#69 Заказ Аристофана на еду.
  Resources/Locale/ru-RU/_RPSX/entities/objects/consumable/food/baked/bread.ftl
  Resources/Locale/ru-RU/_RPSX/entities/objects/consumable/food/baked/pie.ftl
  Resources/Locale/ru-RU/_RPSX/entities/objects/consumable/food/burger.ftl
  Resources/Locale/ru-RU/_RPSX/entities/objects/consumable/food/meals.ftl
  Resources/Locale/ru-RU/_RPSX/entities/objects/consumable/food/meat.ftl
  Resources/Locale/ru-RU/_RPSX/entities/objects/consumable/food/soup.ftl
  Resources/Prototypes/Catalog/VendingMachines/Inventories/boozeomat.yml
  Resources/Prototypes/Corvax/Entities/Mobs/Species/vulpkanin.yml
  Resources/Prototypes/_RPSX/Entities/Objects/Consumable/Drinks/drinks.yml
  Resources/Prototypes/_RPSX/Entities/Objects/Consumable/Drinks/drinks_bottles.yml
  Resources/Prototypes/_RPSX/Entities/Objects/Consumable/Food/Baked/bread.yml
  Resources/Prototypes/_RPSX/Entities/Objects/Consumable/Food/Baked/pie.yml
  Resources/Prototypes/_RPSX/Entities/Objects/Consumable/Food/burger.yml
  Resources/Prototypes/_RPSX/Entities/Objects/Consumable/Food/meals.yml
  Resources/Prototypes/_RPSX/Entities/Objects/Consumable/Food/meat.yml
  Resources/Prototypes/_RPSX/Entities/Objects/Consumable/Food/soup.yml
  Resources/Prototypes/_RPSX/Reagents/drinks.yml
  Resources/Prototypes/_RPSX/Recipes/Construction/Graphs/food/steak.yml
  Resources/Prototypes/_RPSX/Recipes/Cooking/meal_recipes.yml
  Resources/Textures/_RPSX/Objects/Consumable/Drinks/redteaglass.rsi/fill-1.png
  Resources/Textures/_RPSX/Objects/Consumable/Drinks/redteaglass.rsi/fill-2.png
  Resources/Textures/_RPSX/Objects/Consumable/Drinks/redteaglass.rsi/icon.png
  Resources/Textures/_RPSX/Objects/Consumable/Drinks/redteaglass.rsi/icon_empty.png
  Resources/Textures/_RPSX/Objects/Consumable/Drinks/redteaglass.rsi/meta.json
  Resources/Textures/_RPSX/Objects/Consumable/Drinks/teapotred.rsi/meta.json
  Resources/Textures/_RPSX/Objects/Consumable/Drinks/teapotred.rsi/teapotred.png
  Resources/Textures/_RPSX/Objects/Consumable/Food/Baked/bread.rsi/meta.json
  Resources/Textures/_RPSX/Objects/Consumable/Food/Baked/bread.rsi/vbread-slice.png
  Resources/Textures/_RPSX/Objects/Consumable/Food/Baked/bread.rsi/vbread.png
  Resources/Textures/_RPSX/Objects/Consumable/Food/Baked/pie.rsi/meta.json
  Resources/Textures/_RPSX/Objects/Consumable/Food/Baked/pie.rsi/stickytart.png
  Resources/Textures/_RPSX/Objects/Consumable/Food/Bowl/hinkali.rsi/icon.png
  Resources/Textures/_RPSX/Objects/Consumable/Food/Bowl/hinkali.rsi/meta.json
  Resources/Textures/_RPSX/Objects/Consumable/Food/Bowl/lylakebab.rsi/icon.png
  Resources/Textures/_RPSX/Objects/Consumable/Food/Bowl/lylakebab.rsi/meta.json
  Resources/Textures/_RPSX/Objects/Consumable/Food/Bowl/okroshka.rsi/meta.json
  Resources/Textures/_RPSX/Objects/Consumable/Food/Bowl/okroshka.rsi/okroshka.png
  Resources/Textures/_RPSX/Objects/Consumable/Food/Bowl/olive.rsi/meta.json
  Resources/Textures/_RPSX/Objects/Consumable/Food/Bowl/olive.rsi/olive.png
  Resources/Textures/_RPSX/Objects/Consumable/Food/Meals/khachapyri.rsi/icon.png
  Resources/Textures/_RPSX/Objects/Consumable/Food/Meals/khachapyri.rsi/meta.json
  Resources/Textures/_RPSX/Objects/Consumable/Food/bowl/ClamSoup.rsi/clamsoup.png
  Resources/Textures/_RPSX/Objects/Consumable/Food/bowl/ClamSoup.rsi/meta.json
  Resources/Textures/_RPSX/Objects/Consumable/Food/bowl/SlugRice.rsi/meta.json
  Resources/Textures/_RPSX/Objects/Consumable/Food/bowl/SlugRice.rsi/slugrice.png
  Resources/Textures/_RPSX/Objects/Consumable/Food/bowl/VulpSoup.rsi/meta.json
  Resources/Textures/_RPSX/Objects/Consumable/Food/bowl/VulpSoup.rsi/vulposoup.png
  Resources/Textures/_RPSX/Objects/Consumable/Food/burger.rsi/meta.json
  Resources/Textures/_RPSX/Objects/Consumable/Food/burger.rsi/vulburger.png
  Resources/Textures/_RPSX/Objects/Consumable/Food/meat.rsi/meat-vulp-cooked.png
  Resources/Textures/_RPSX/Objects/Consumable/Food/meat.rsi/meat-vulp.png
  Resources/Textures/_RPSX/Objects/Consumable/Food/meat.rsi/meta.json
Labels: size/M, Changes: No C#, Changes: Sprites

#89 Правки
  Resources/Locale/ru-RU/engineer-painter/engineer-painter.ftl
  Resources/Locale/ru-RU/guidebook/chemistry/effects.ftl
  Resources/Locale/ru-RU/health-examinable/health-examinable-silicon.ftl
  Resources/Locale/ru-RU/markings/vox_tattoos.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/corvax/objectives/traitorObjectives.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/darkstation/maingame/entities/objects/misc/identification_cards.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/outerclothing/armor.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/outerclothing/vests.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/markers/spawners/random/vendinclothes.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/mobs/npcs/animals.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/mobs/player/silicon.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/consumable/drinks/drinks_flasks.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/fun/instruments/instruments_percussion.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/fun/instruments/instruments_wind.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/misc/spider_web.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/weapons/throwable/clusterbang.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/weapons/throwable/scattering_grenades.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/gamerules/midround.ftl
  Resources/Locale/ru-RU/xenoarchaeology/artifact-component.ftl
Labels: size/M, Changes: No C#
