Repository rp-s-tech/SS14_Workstation, pull requests merged in 2025-06, with the labels that each got.

#43 mb attributions fix
  .github/workflows/labeler-untriaged.yml
  Resources/Audio/_RPSX/Announcements/attributions.yml
  Resources/Audio/_RPSX/Effects/Barking/attributions.yml
  Resources/Audio/_RPSX/Effects/Whines/attributions.yml
Labels: size/S, Changes: No C#

#44 capacitors and matterbins removing
  Resources/Prototypes/Corvax/Entities/Objects/Devices/Circuitboards/Machine/production.yml
  Resources/Prototypes/DarkStation/MainGame/Entities/Structures/Machines/lathe.yml
  Resources/Prototypes/DarkStation/MainGame/Entities/Structures/Machines/rimworldrecipes.yml
Labels: Changes: No C#

#45 surgery, pda and action fixes
  Resources/Prototypes/Body/Parts/reptilian.yml
  Resources/Prototypes/DarkStation/MainGame/Roles/Jobs/Medical/pathologist.yml
  Resources/Prototypes/DarkStation/MainGame/Roles/Jobs/Medical/surger.yml
  Resources/Prototypes/DarkStation/MainGame/Sponsors/actions.yml
Labels: size/S, Changes: No C#

#47 Update/Fixes locales
  Resources/Locale/ru-RU/_RPSX/actions/actions/vampire.ftl
  Resources/Locale/ru-RU/_units.ftl
  Resources/Locale/ru-RU/actions/actions/internals.ftl
  Resources/Locale/ru-RU/actions/actions/rootable.ftl
  Resources/Locale/ru-RU/advertisements/other/medibot.ftl
  Resources/Locale/ru-RU/advertisements/vending/bruiseomat.ftl
  Resources/Locale/ru-RU/advertisements/vending/robodrobe.ftl
  Resources/Locale/ru-RU/alerts/alerts.ftl
  Resources/Locale/ru-RU/arcade/blockgame.ftl
  Resources/Locale/ru-RU/cargo/bounties.ftl
  Resources/Locale/ru-RU/chat/managers/chat-manager.ftl
  Resources/Locale/ru-RU/ghost/roles/ghost-role-component.ftl
  Resources/Locale/ru-RU/holopad/holopad.ftl
  Resources/Locale/ru-RU/lobby/lobby-gui.ftl
  Resources/Locale/ru-RU/machine-linking/receiver_ports.ftl
  Resources/Locale/ru-RU/machine-linking/transmitter_ports.ftl
  Resources/Locale/ru-RU/ninja/ninja-actions.ftl
  Resources/Locale/ru-RU/nutrition/components/food-sequence.ftl
  Resources/Locale/ru-RU/prototypes/roles/antags.ftl
  Resources/Locale/ru-RU/quick-dialog/quick-dialog.ftl
  Resources/Locale/ru-RU/recipes/components.ftl
  Resources/Locale/ru-RU/shuttles/timer.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/actions/types.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/markers/spawners/random/department/medical.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/markers/spawners/random/department/science.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/markers/spawners/random/department/security.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/specific/xenoarchaeology/item_artifacts.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/specific/xenoarchaeology/item_xenoartifacts.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/specific/xenoarchaeology/structure_artifacts.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/specific/xenoarchaeology/structure_xenoartifacts.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/specific/xenoarchaeology/xenoartifacts.ftl
  Resources/Locale/ru-RU/station-laws/laws.ftl
  Resources/Locale/ru-RU/storage/components/secret-stash-component.ftl
  Resources/Locale/ru-RU/store/currency.ftl
  Resources/Locale/ru-RU/store/pai-catalog.ftl
  Resources/Locale/ru-RU/store/spellbook-catalog.ftl
  Resources/Locale/ru-RU/store/uplink-catalog.ftl
  Resources/Locale/ru-RU/teleportation/teleportation-menu-gui.ftl
  Resources/Locale/ru-RU/traits/traits.ftl
  Resources/Prototypes/DarkStation/MainGame/DarkForces/Vampire/Abilities/abilities.yml
Labels: size/M, Changes: No C#

#51 VampireWindowFIx
  Content.Server/_RPSX/GameRules/Vampire/EUI/VampireAbilitiesEUI.cs
  Content.Server/_RPSX/GameRules/Vampire/Role/VampireSystem.cs
  Content.Shared/_RPSX/DarkForces/Vampire/Components/VampireComponent.cs
Labels: size/S, S: Untriaged

#48 Update loadout_groups.yml
  Resources/Prototypes/Loadouts/Miscellaneous/trinkets.yml
  Resources/Prototypes/Loadouts/loadout_groups.yml
Labels: size/XS, Changes: No C#, S: Untriaged
